name: Continuous Delivery

on:
  push:
    tags: 'v*'  # push events to matching v*, i.e. v1.0, v20.15.10

env:
  PYTHON_DEFAULT_VERSION: 3.9
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - name: Create GitHub release
        id: create-release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: true
  deploy-bundle:
    needs: deploy
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, macos-10.15]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_DEFAULT_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_DEFAULT_VERSION }}
      - name: Install dependencies
        run: |
          cd python-bindings
          python -m pip install --upgrade nox pip
      - name: Bundle the distribution
        id: bundle
        run: |
          cd python-bindings
          nox -vs bundle
      - name: Upload the distribution to GitHub
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.deploy.outputs.upload_url }}
          asset_path: python-bindings/${{ steps.bundle.outputs.asset_path }}
          asset_name: ${{ steps.bundle.outputs.asset_name }}
          asset_content_type: application/octet-stream
